# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Projects/ERN24004/Projects/PMOD_AD1_DMA/PMOD_AD1_DMA.srcs/sources_1/bd/dma/ip/dma_xbar_1/dma_xbar_1.xci
# IP: The module: 'dma_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/ERN24004/Projects/PMOD_AD1_DMA/PMOD_AD1_DMA.gen/sources_1/bd/dma/ip/dma_xbar_1/dma_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Projects/ERN24004/Projects/PMOD_AD1_DMA/PMOD_AD1_DMA.srcs/sources_1/bd/dma/ip/dma_xbar_1/dma_xbar_1.xci
# IP: The module: 'dma_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/ERN24004/Projects/PMOD_AD1_DMA/PMOD_AD1_DMA.gen/sources_1/bd/dma/ip/dma_xbar_1/dma_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
